name: List files

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  list:
    runs-on: clemens
    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: List files in repo
        run: tree .
      - name: List files in repo
        run: ls /
      - run: sudo apt update
