name: List files

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  list:
    environment: prod
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: List files in repo
        run: tree .

  call-workflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      who-to-greet: 'Mona'

  read-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - name: Read outputs
        run: echo "The greeting is ${{ needs.call-workflow.outputs.greeting }} and the current time is ${{ needs.call-workflow.outputs.current-time }}"
