name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet: 
        required: true
        description: 'Who to greet'
        default: 'World'
        type: string
    outputs:
      greeting: 
        description: 'The greeting'
        value: '${{ jobs.greet.outputs.greeting }}'
      current-time: 
        description: 'The current time'
        value: '${{ jobs.greet.outputs.current-time }}'
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'
  
jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      greeting: ${{ steps.set-outputs.outputs.greeting }}
      current-time: ${{ steps.set-outputs.outputs.current-time }}
    steps:
      - name: Greet
        run: echo "Hello, ${{ inputs.who-to-greet }}!"
      - name: Set outputs
        id: set-outputs
        run: echo "greeting=Hello, ${{ inputs.who-to-greet }}" >> $GITHUB_OUTPUT && echo "current-time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
      - name: use outputs
        run: echo "The greeting is ${{ steps.set-outputs.outputs.greeting }} and the current time is ${{ steps.set-outputs.outputs.current-time }}"
